### ISSUE TITLE
Bug: `samples/mkdocs-material`: Table of Contents indexes incorrectly when the PDF truncates.

### ISSUE THREAD

**Issue by domWalters** [domWalters/mkdocs-to-pdf#35]
Related to #34 

When #34 happens, the ToC has the page of all missing sections set to 0.

![Image](https://github.com/user-attachments/assets/f6fcf4e3-1062-4a4a-ae46-799835cea524)

**Comment by dpinol** [comment]
What I realized is that these syntaxes work:

```
nav:
  - section1: section1.md
  - section2:
      - page1: page1.md
```

But this one doesn't:
```
nav:
  - section1:
      - page1.md
```

**Comment by nihalshah-dev** [comment]
@dpinol That shouldn't be the case. My nav structure looks like below and still it doesn't work..

```yaml
nav:
- 'Project ABC':
  - 'Getting Started': 'file.md'
  - 'Overview':
    - 'Topic 1': 
        - 'Sub-topic1': 'file.md'
        - 'Sub-topic2': 'file.md'
    - 'Topic 2':
        - 'Sub-topic1': 'file.md'
    - 'Topic 3': 'file.md'
  - 'Troubleshooting': 'file.md'
  - 'Contributing': 'file.md'
  - 'Release Notes':
    - 'Topic 1':
          - 'Sub-topic1': 
              - 'Sub-topic1': 'file.md'
    - 'Examples':
          - 'Topic 1': 'file.md'
          - 'Topic 2':
              - 'Sub-topic1': 'file.md'
          - 'Topic 3': 'file.md'
    - 'Glossary': 'file.md'
```
