### ISSUE TITLE
Proposal: change default under line color, font color, etc

### ISSUE THREAD

**Issue by hkato** [domWalters/mkdocs-to-pdf#47]
@domWalters 

by dafault

- Underlining the cover page and headings : red -> black
- Headings: gray -> black
- h5, h6, etc: too small -> change size

For example, some people would like to change the color.

- https://github.com/orzih/mkdocs-with-pdf/issues/119
- https://github.com/orzih/mkdocs-with-pdf/issues/153
- https://github.com/orzih/mkdocs-with-pdf/issues/124

Therefore, by default, plain black is more suitable for PDF/paper documents.

In the future, add documentation on how to customize `templates/styles.scss`

```css
@media print {
    article h1, article h2, article h3 {
        border-bottom-color: red !important;
    }
}
```

**Comment by hkato** [comment]
@domWalters 

I would like to change the default print style. For example, the underlinings are currently red, and I don't think it looks good. What are your thoughts on this?

This is my current `templates/styles.scss` file. I want to change this kind of style by default. (`src/mkdocs_to_pdf/styles/*.scss`)

Sorry for inconvenience, SCSS comments are Japanese.

```css
@media print {
  // 小さすぎて見にくいので変更
  pre,
  code,
  var,
  samp,
  kbd,
  tt {
    font-size: 1em;
  }

  // グレーに赤系のアンダーラインで見にくいのに派手なので変更
  article h1,
  article h2,
  article h3 {
    color: black !important;
    font-weight: normal !important;
    border-color: #a9a9a9 !important;
  }
  // サイズが小さくなりボールドになっていくので見にくいので変更
  article h4,
  article h5,
  article h6 {
    color: black !important;
    font-size: 1em !important;
    font-weight: normal !important;
  }
}

@page {
  // 各ページのヘッダーフッターがグレーなので見にくいので変更
  color: black;
  // コピーライト表記が小さいので大きくする
  @bottom-right {
    font-size: 8pt;
  }
}
```
