### ISSUE TITLE
Path problem - add logo to scss for @top-left

### ISSUE THREAD

**Issue by Privatacc** [domWalters/mkdocs-to-pdf#65]
Hello, i have a problem to use the path to a local img in my scss file. 
I tried to add the path relative to my docs folder, but it doesn't work. I also tried it with an image from a web url and it worked, but i need it for a local image. I need the logo for every page except the first one.

Code snippet:

@page {
  size: a4 portrait;
  margin: 25mm 10mm 25mm 10mm;
  counter-increment: page;
  white-space: pre;
  color: grey;

  @top-right {
    margin-right: 3mm;  
  }

  **@top-left{
    content: url('../docs/assets/img/x.png');**
    width: 50px;
    height: 50px; 
  }

@page :first { 
  @top-left {
    content: normal;
  }
};

Folder structure:

projekt/
└── docs/
        ├── assets/
        │      └── img/
        │              └── x.png
        ├── css/
        │      └── styles.css 
        └── scss/
                └── styles.scss

Thanks for your help.

**Comment by hkato** [comment]
For now, I cannot provide a solution using local files.
However, what about this approach: data: URLs?
https://developer.mozilla.org/en-US/docs/Web/URI/Reference/Schemes/data
```css
@page {
  @top-left {
    content: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyBAMAAADsEZWCAAAAD1BMVEXMzMwAAACysrJ/f3+ZmZnNdseSAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAV0lEQVQ4je2PsQ3AIAwEXzaDWMAAluIBEHj/mULSQUrK+JovTv/SA0FwRgY9QQJZBVk2nVl6GatJnaEtwUV56/iAsqL6boDrNeBPZ3Rrc61a8dMzwe+5AfMSB5OrW8+qAAAAAElFTkSuQmCC");
  }
}
```

I'm not certain, but it seems like we should look into WeasyPrint.

**Comment by hkato** [comment]
> I need the logo for every page except the first one.

```css
@page : first {
  @top-left {
    content: "";
  }
}
@page {
  @top-left {
    content: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADIAAAAyBAMAAADsEZWCAAAAD1BMVEXMzMwAAACysrJ/f3+ZmZnNdseSAAAACXBIWXMAAA7EAAAOxAGVKw4bAAAAV0lEQVQ4je2PsQ3AIAwEXzaDWMAAluIBEHj/mULSQUrK+JovTv/SA0FwRgY9QQJZBVk2nVl6GatJnaEtwUV56/iAsqL6boDrNeBPZ3Rrc61a8dMzwe+5AfMSB5OrW8+qAAAAAElFTkSuQmCC");
  }
}
```

**Comment by hkato** [comment]
How about this?

1024x768 XGA image -> 100 x 50 logo

<img width="428" alt="Image" src="https://github.com/user-attachments/assets/79e30fcc-a4ca-41a8-86c5-e670932ac2a6" />

- content: ""
- background-image

```css
@page : first {
  @top-left {
    content: normal;
  }
}
@page {
  @top-left {
    content: "";
    background-image: url("https://dummyimage.com/1024x768/");
    background-repeat: no-repeat;
    background-size: 100px 50px;
    background-position: top left;
    width: 100px;
    height: 50px;
  }
}
```
