### ISSUE TITLE
Bug (old): Images specifics to theme palette are displayed on PDF

### ISSUE THREAD

**Issue by Thiti517** [domWalters/mkdocs-to-pdf#73]
## Old bug (Inherited from Parent Project)

♻ *This issue originates from the parent project: [orzih/mkdocs-with-pdf#149](https://github.com/orzih/mkdocs-with-pdf/issues/149)*

When using [light and dark mode images](https://squidfunk.github.io/mkdocs-material/reference/images/?h=images#light-and-dark-mode) from material, all variant images (`#only-light`, `#only-dark`) are visible in the PDF.

Since PDFs are usually viewed or printed on a light (white) background, only the light-mode versions should appear. But, both versions are currently visible, leading to confusion.

## Proposed fix

Add the following CSS to hide dark-only images when generating the PDF:

```css
/* Hide dark mode images in PDF output */
.md-typeset img[src$="#only-dark"],
.md-typeset figure img[src$="#only-dark"] {
    display: none;
}
```
(I added the second selector for my figures plugin but since [material support figure](https://squidfunk.github.io/mkdocs-material/reference/images/?h=images#image-captions), it should be included as well

It would makes sense to include this in `material.scss`, but I’m not sure.

**Comment by hkato** [comment]
I haven't used MkDocs with light/dark mode yet.

With these minimal settings, the issue was reproduced. And it's fixed with your CSS in the `templates/styles.scss` file.

> It would makes sense to include this in material.scss, but I’m not sure.

@Thiti517 @domWalters 

I think it might be a good idea to add this to `material.scss`.

```yaml
site_name: My Docs

theme: 
  name: material
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins: 
  - to-pdf
```

```markdown
# Welcome to MkDocs

![Image title](https://dummyimage.com/600x400/f5f5f5/aaaaaa#only-light)
![Image title](https://dummyimage.com/600x400/21222c/d5d7e2#only-dark)
```
