### ISSUE TITLE
Feature Request: Option to Exclude HTML/CSS Elements from PDF Output

### ISSUE THREAD

**Issue by nihalshah-dev** [domWalters/mkdocs-to-pdf#75]
Hi Again😅,

## Problem Statement
I have integrated a feedback button on my MkDocs website using custom HTML and CSS. This button is essential for the web build , but it unnecessarily appears on every page of the generated PDF.

The button includes styling and potential animation effects that are irrelevant and distracting in the context of a PDF document.

see -
![Image](https://github.com/user-attachments/assets/70eed4ab-482d-42dc-8200-47100b87255c)

## Current Behavior
The mkdocs-to-pdf plugin currently includes all rendered HTML/CSS, including custom elements like the feedback button, into the final PDF.

The existing options like exclude_pages and exclude_children exclude whole pages, TOC, & headings, but they don't solve the problem of excluding specific HTML/CSS fragments.

## Expected Behavior
I would like the plugin to exclude certain HTML or CSS components (like floating feedback buttons or web-only animations) from the PDF output. I 
 see couple of ways this could be supported:

Either a New Option :
Allow users to specify CSS selectors that should be excluded when generating the PDF.

something like this-
```
plugins:
    - to-pdf:
        excludes_children:
            - 'release-notes/:upgrading'
            - 'release-notes/:changelog'
        exclude_pages:
            - 'bugs/'
            - 'appendix/contribute/'
       exclude_elements: 
            - "assets/stylesheets/feedback-button.css"
```

Or Default Handling :
Automatically detect and ignore floating or absolutely-positioned elements meant only for the web view.

@hkato @domWalters @Thiti517 Let me know if the use case is understandable and if you need additional inputs from me?
