### ISSUE TITLE
PDF not being generated

### ISSUE THREAD

**Issue by ladytamz** [domWalters/mkdocs-to-pdf#79]
Hi, I'm attempting to generate a PDF using the mkdocs-to-pdf plugin. I'm using the following in my mkdocs.yml file:
```
plugins:
    - to-pdf:
        author: [mycompany]
        output_path: ./[my-file-name].pdf

```
However when I run the mkdocs build command, the build  happens without creating a PDF file.

The info messages I'm receiving are as follows:
```
INFO    -  Cleaning site directory
INFO    -  Building documentation to directory: C:\[my-directory]\[my-folder-name]\site
INFO    -  Documentation built in 1.51 seconds
```

Can you help me troubleshoot and understand why the plugin isn't building a PDF file?

**Comment by hkato** [comment]
Hello, Do you use Windows OS?

I usually use macOS, and @domWalters uses Linux. I have a Windows 10 PC, and I tried this minimal configuration and it worked fine. 

```yaml
site_name: My Docs

theme:
  name: material

plugins:
  to-pdf:
    author: acme company
    output_path: ./foo-bar.pdf
```

Have you installed GTK+? If not, please install it (see #59).

**Comment by ladytamz** [comment]
Hi, I'm using Windows OS, yes. I don't think I installed GTK. I'll try that and see if it helps. Thanks for your answer!

**Comment by ladytamz** [comment]
Ok, so I installed GTK and tried the other suggestions in issue #59. Now I'm finally getting a PDF output but it's only outputting the first 69 pages or so of the thousand page document. But I see that there's another issue that addresses that, so I'll go take a look at that and see if it resolves my new issue.

**Comment by ladytamz** [comment]
Update, I've checked the other issue and their problem seems to have been with one of their plugins, and these are the only plugins I'm using:

```
plugins:
    - to-pdf:
        author: [mycompany]
        output_path: ./[my doc name].pdf
    - search:
        separator: '[\s\-\_]'
```

So it doesn't seem likely to be the same issue. If you can help me troubleshoot further, I'd be most apprecative. Let me know if there's any additional info you need to help.

**Comment by Thiti517** [comment]
Hello there,

## Related Issues

This may be related to: #34, #35, #62, or #74.

## Identifying the Problem

If PDF generation stops *mid-way*, check the **Table of Contents (ToC)** and look for the first section listed on **page 0**, this usually indicates where the rendering failed.

Then, inspect the corresponding Markdown source for one of the following common causes:

- A large list that spans more than one page
- A large table that spans more than one page
- A large code block that spans more than one page
- An image that doesn’t fit on a single page

## Quick Fixes (Workarounds)

### Large Lists and Tables

You can try adding a CSS file in `extra_css` option to allow page breaks inside large lists or tables, after a certain number of children:

```css
@media print {
    /* Apply styles to long lists or tables (20+ items) */
    ul:has(li:nth-child(n+21)),
    ol:has(li:nth-child(n+21)),
    table:has(tr:nth-child(n+21)) {
        border: solid 5px red !important; /* Temporary debug border, remove when confirmed working */
        page-break-inside: auto;
    }

    /* Avoid splitting individual items across pages */
    li, tr {
        page-break-inside: avoid;
    }
}
```

✏ **Note**: The `n+21` is an arbitrary number, adjust it to fit your needs.

See this workaround source: [Issue #74](https://github.com/domWalters/mkdocs-to-pdf/issues/74#issuecomment-2882744308)

### Large Code Blocks

Avoid using these options in the `pymdownx.highlight` extension, as they may break PDF generation due to page size limitations:

- [`linenums`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#pymdownx.highlight.linenums)
- [`linenums_style`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#pymdownx.highlight.linenums_style)
- [`anchor_linenums`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#pymdownx.highlight.anchor_linenums)
- [`line_spans`](https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/#pymdownx.highlight.line_spans)

Even if not always problematic, these settings can contribute to layout failures. Alternatively you can try keeping code blocks reasonably small in both width (characters per line) and height (number of lines).

Related to issue #62

### Large Images

Resize images to more standard dimensions before rendering.

## Addendum

These workarounds are... workarounds (obviously), they might not always work and are clearly not real solutions to the global 
***PDF generation break*** issue.

Hope it helped a little :D

**Comment by ladytamz** [comment]
That helped a lot, thank you. My document does have a few long tables that span several pages, and it also has many code blocks that span multiple pages. I'm guessing one of those is the culprit.

I'm a bit of a newbie when it comes to CSS though. Can you tell me where I would add the CSS file (that is, would it be on the same level as the mkdocs.yml file), and how I'd add it to my yaml file?

Thanks so much for your help!

**Comment by Thiti517** [comment]
That good but **before applying any workarounds first take a look at what exactly break the PDF generation** by looking at ToC

> If PDF generation stops _mid-way_, check the **Table of Contents (ToC)** and look for the first section listed on **page 0**, this usually indicates where the rendering failed.
> 
> Then, inspect the corresponding Markdown source for one of the following common causes:
> 
> - A large list that spans more than one page
> - A large table that spans more than one page
> - A large code block that spans more than one page
> - An image that doesn’t fit on a single page

Now, to apply custom CSS to MkDocs documentation here is a quick guide:

1. Create a CSS file inside your docs directory. (i recommend: `docs/assets/styles/pdf-fix.css`)
2. Add the [previously shared CSS rules](https://github.com/domWalters/mkdocs-to-pdf/issues/79#issuecomment-2909056817) in the newly created file `pdf-fix.css`:
```css
@media print {
    /* Apply styles to long lists or tables (20+ items) */
    ul:has(li:nth-child(n+21)),
    ol:has(li:nth-child(n+21)),
    table:has(tr:nth-child(n+21)) {
        border: solid 5px red !important; /* Temporary debug border, remove when confirmed working */
        page-break-inside: auto;
    }

    /* Avoid splitting individual items across pages */
    li, tr {
        page-break-inside: avoid;
    }
}
```
3. Reference the CSS file in the mkdocs config by adding this option in `mkdocs.yml`:
```yaml
extra_css:
  - assets/styles/pdf-fix.css # This is relative to `docs` directory
```
4. Build the doc and check the result

Your file structure should look like so
```tree
./
├── mkdocs.yml
└── docs/
    ├── assets/
    │   └── styles/
    │       └── pdf-fix.css
    └── index.md
```
