### ISSUE TITLE
Error building the MKDOCS Repo

### ISSUE THREAD

**Issue by aya-elalfy** [domWalters/mkdocs-to-pdf#80]
I am currently facing a build error issue whenever i try to use the plugin 

![Image](https://github.com/user-attachments/assets/4d6f93fc-80a7-421c-9682-2079880d43bf)

knowing that error doesn't happen when i use mkdocs-with-pdf plugin 
any help how to overcome this error ?

**Comment by domWalters** [comment]
Hi,

Can you provide the version number of the plugin that you are using?

What does `pip freeze -all` say for your virtual environment?

**Comment by aya-elalfy** [comment]
version 0.10.1
and this is the output for the pip command 

![Image](https://github.com/user-attachments/assets/06a3f8ce-860f-46d6-8aca-8f6e43cc2dc6)

![Image](https://github.com/user-attachments/assets/c6304206-2d4d-44a0-afc4-4a331bdcd8c9)

**Comment by domWalters** [comment]
I believe this is fixed on current `develop`:

https://github.com/domWalters/mkdocs-to-pdf/commit/c38702c01bc27c8855ad70ee1860cd622ec83a94

This issue is related: https://github.com/domWalters/mkdocs-to-pdf/issues/66

Are you able to try `develop` rather than `v0.10.1`?

---

Edit: If this works, and you need a version pushed, I may be able to generate a `v0.10.2` this evening.

**Comment by aya-elalfy** [comment]
I have tried it and now it works, thank @domWalters 
but now the generated pdf has this issue
color codes overwrites the words like this :

![Image](https://github.com/user-attachments/assets/28e63950-61ae-45b8-8fac-8b7eebb95428)

**Comment by Thiti517** [comment]
> I have tried it and now it works, thank [@domWalters](https://github.com/domWalters) but now the generated pdf has this issue color codes overwrites the words like this :
> 
> ![Image](https://github.com/user-attachments/assets/28e63950-61ae-45b8-8fac-8b7eebb95428)

Hello !

I assume you are using [custom admonitions](https://squidfunk.github.io/mkdocs-material/reference/admonitions/#custom-admonitions) in your documentation. In which case you will need to add some "*hacky*" CSS to transform admonition icons since *Weasyprint* does not support `mask-image` CSS property that *Material for MkDocs* use to render admonition icons.

Add this css to you code for each custom admonitions you've created:

```css
:root {
  --print-md-admonition-icon--__ADMONITION_NAME__: url('data:image/svg+xml;charset=utf-8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="%23__HEX_COLOR__">__SVG_PATH__</svg>');
}
@media print {
  .md-typeset .__ADMONITION_NAME__ > .admonition-title,
  .md-typeset .__ADMONITION_NAME__> summary {
    padding: 0.6rem 0.6rem 0.4rem 2.2rem;
  }
  .md-typeset .__ADMONITION_NAME__> .admonition-title::before,
  .md-typeset .__ADMONITION_NAME__> summary::before {
    margin-top: -0.15rem;
    background-color: transparent;
    background-image: var(--print-md-admonition-icon--__ADMONITION_NAME__);
    background-repeat: no-repeat;
  }
}
```

**Remember to change these placeholders with accurate values**:

- **`__ADMONITION_NAME__`** : the name used to reference the admonition
- **`__HEX_COLOR__`** : Fill color in SVG without `#`
- **`__SVG_PATH__`** : the SVG path inside SVG tag
